version: 2.1
orbs:
  node: circleci/node@5.0.1
  aws-cli: circleci/aws-cli@1.3.1
  eb: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      # adding AWS CLI
      - aws-cli/setup
      # adding nodejs
      - node/install
      # adding elb
      - eb/setup
      - run:
      # adding frontend files
          name: Front-end install
          command: |
            npm run frontend:install
      - run:
      # building frontend
          name: Front-end Build
          command: |
            npm run frontend:build
      - run:
      # deploying frontend using AWS CLI
          name: Front-end Deploy
          command: |
            cd udagram/udagram-frontend
            aws s3 cp --recursive --acl public-read ./www s3://udagram-ui-bk/
      - run:
      # instaling backend files
          name: Back-end Install
          command: |
            npm run api:install
      - run:
      # building backend
          name: Back-end Build
          command: |
            npm run api:build
      - run:
            # deploying back-end using elb CLI
          name: Back-end Deploy
          command: |
            eb init --region us-east-1 --platform node.js Udagramapi-env
            npm run api:deploy
workflows:
  build-deploy:
    jobs:
      - build:
        filters:
          branches:
            only: 
              - main